name: Drop the database associated with the PR

on:
    pull_request:
        types: [closed]

env:
    target_db_name: pr-${{ github.event.number }}
    neon_project_id: fancy-mouse-984056
    neon_api_key: ${{ secrets.NEON_API_KEY }}

jobs:
    drop-db:
        runs-on: ubuntu-latest
        steps:
            - name: Drop the PR database
              run: |
                  curl -X DELETE "https://console.neon.tech/api/v1/projects/${{ env.neon_project_id }}/databases/$(curl -X GET 'https://console.neon.tech/api/v1/projects/${{ env.neon_project_id }}/databases' -H 'accept: application/json' -H 'Authorization: Bearer ${{ env.neon_api_key }}' | jq -c '.[] | select(.name | inside(\"${{ env.target_db_name }}\")) | .id')" \
                      -H 'accept: application/json' \
                      -H 'Content-Type: application/json' \
                      -H 'Authorization: Bearer ${{ env.neon_api_key }}'
